definitions:
  handler.RegisterRequest:
    properties:
      confirmPassword:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.ProfileUser:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      imageURL:
        type: string
      language:
        type: string
      phone_number:
        type: string
      role:
        type: string
      status_user:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  model.Snack:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Ini adalah API server untuk aplikasi E-Meeting.
  title: E-Meeting API
  version: "1.0"
paths:
  /profile/:id:
    get:
      consumes:
      - application/json
      description: Mengambil data profile berdasarkan id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ProfileUser'
            type: array
      summary: Mendapatkan data profile
      tags:
      - Profile
  /register:
    post:
      consumes:
      - application/json
      description: Register user baru
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Register Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register user baru
      tags:
      - Register
  /rooms:
    get:
      consumes:
      - application/json
      description: Mengambil seluruh daftar room yang tersedia dengan filter dan pagination
      parameters:
      - description: Nama ruangan
        in: query
        name: name
        type: string
      - description: Tipe ruangan
        in: query
        name: type
        type: string
      - description: Kapasitas minimal
        in: query
        name: capacity
        type: integer
      - default: 1
        description: Nomor halaman
        in: query
        name: page
        type: integer
      - default: 20
        description: Jumlah data per halaman
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Mendapatkan semua data room
      tags:
      - Rooms
  /snacks:
    get:
      consumes:
      - application/json
      description: Mengambil seluruh daftar snack yang tersedia
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Snack'
            type: array
      summary: Mendapatkan semua data snack
      tags:
      - Snacks
swagger: "2.0"
