definitions:
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.ProfileUser:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      imageURL:
        type: string
      language:
        type: string
      phone_number:
        type: string
      role:
        type: string
      status_user:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  model.RegisterRequest:
    properties:
      confirmPassword:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.ReservationCalculationData:
    properties:
      personalData:
        $ref: '#/definitions/model.ReservationCalculationPersonalData'
      rooms:
        items:
          $ref: '#/definitions/model.ReservationCalculationRooms'
        type: array
    type: object
  model.ReservationCalculationPersonalData:
    properties:
      company:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
    type: object
  model.ReservationCalculationResponse:
    properties:
      data:
        $ref: '#/definitions/model.ReservationCalculationData'
      message:
        type: string
      subTotalRoom:
        format: float64
        type: number
      subTotalSnack:
        format: float64
        type: number
      total:
        format: float64
        type: number
    type: object
  model.ReservationCalculationRooms:
    properties:
      capacity:
        type: integer
      duration:
        type: integer
      endTime:
        type: string
      imagesUrl:
        type: string
      name:
        type: string
      participant:
        type: integer
      pricePerHour:
        format: float64
        type: number
      snack:
        $ref: '#/definitions/model.ReservationCalculationSnack'
      startTime:
        type: string
      subTotalRooms:
        format: float64
        type: number
      subTotalSnack:
        format: float64
        type: number
      type:
        type: string
    type: object
  model.ReservationCalculationSnack:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        description: unit string
        format: float64
        type: number
    type: object
  model.ReservationRequest:
    properties:
      company:
        example: ABC Company
        type: string
      name:
        example: John Doe
        type: string
      notes:
        example: Special request
        type: string
      phoneNumber:
        example: "081234567890"
        type: string
      rooms:
        items:
          $ref: '#/definitions/model.RoomRequest'
        type: array
      userID:
        example: "1"
        type: string
    type: object
  model.RoomRequest:
    properties:
      endTime:
        example: "2025-10-17T14:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      participant:
        example: 2
        type: integer
      snackID:
        example: 1
        type: integer
      startTime:
        example: "2025-10-17T12:00:00Z"
        type: string
    type: object
  model.Snack:
    properties:
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      unit:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Ini adalah API server untuk aplikasi E-Meeting.
  title: E-Meeting API
  version: "1.0"
paths:
  /profile/:id:
    get:
      consumes:
      - application/json
      description: Mengambil data profile berdasarkan id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ProfileUser'
            type: array
      summary: Mendapatkan data profile
      tags:
      - Profile
  /register:
    post:
      consumes:
      - application/json
      description: Register user baru
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Register Success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register user baru
      tags:
      - Register
  /reservation/calculation:
    get:
      consumes:
      - application/json
      description: Hitung total biaya reservasi berdasarkan room, snack, waktu, dan
        peserta
      parameters:
      - description: ID ruangan
        in: query
        name: room_id
        required: true
        type: integer
      - description: ID snack (optional)
        in: query
        name: snack_id
        type: integer
      - description: Waktu mulai (format RFC3339)
        in: query
        name: startTime
        required: true
        type: string
      - description: Waktu selesai (format RFC3339)
        in: query
        name: endTime
        required: true
        type: string
      - description: Jumlah peserta
        in: query
        name: participant
        required: true
        type: integer
      - description: ID user (optional)
        in: query
        name: user_id
        type: integer
      - description: Nama pemesan
        in: query
        name: name
        type: string
      - description: Nomor telepon pemesan
        in: query
        name: phoneNumber
        type: string
      - description: Nama perusahaan
        in: query
        name: company
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.ReservationCalculationResponse'
        "400":
          description: Bad Request - over capacity / booking bentrok
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Reservation Calculation
      tags:
      - Reservation
  /reservations:
    post:
      consumes:
      - application/json
      description: Create a new meeting room reservation with room details and snacks
      parameters:
      - description: Reservation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ReservationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: reservation created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: invalid request / room not found / room has been booked / invalid
            userID
          schema:
            additionalProperties: true
            type: object
        "401":
          description: unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new reservation
      tags:
      - Reservations
  /rooms:
    get:
      consumes:
      - application/json
      description: Mengambil seluruh daftar room yang tersedia dengan filter dan pagination
      parameters:
      - description: Nama ruangan
        in: query
        name: name
        type: string
      - description: Tipe ruangan
        in: query
        name: type
        type: string
      - description: Kapasitas minimal
        in: query
        name: capacity
        type: integer
      - default: 1
        description: Nomor halaman
        in: query
        name: page
        type: integer
      - default: 20
        description: Jumlah data per halaman
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Mendapatkan semua data room
      tags:
      - Rooms
  /snacks:
    get:
      consumes:
      - application/json
      description: Mengambil seluruh daftar snack yang tersedia
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Snack'
            type: array
      summary: Mendapatkan semua data snack
      tags:
      - Snacks
swagger: "2.0"
